apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-checker
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-checker
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-checker
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-checker
subjects:
- kind: ServiceAccount
  name: cert-checker
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cert-expiry-checker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-expiry-checker
  template:
    metadata:
      labels:
        app: cert-expiry-checker
    spec:
      serviceAccountName: cert-checker
      containers:
        - name: cert-expiry-checker
          image: zachomedia/k8s-https-check:main
          imagePullPolicy: Always
